---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(pinyin)
```

`charToRaw` from `base` package seems to be the key!

ā á ǎ à ē é ě è ī í ǐ ì ō ó ǒ ò ū ú ǔ ù ǖ ǘ ǚ ǜ 

pinyin::py Able to retrieve pinyin for character

https://github.com/pzhaonet/pinyin

## Preload data and dictionaries

```{r}
anki_cards <- read_tsv("191013_story_notes.txt", locale = readr::locale(encoding="UTF-8"), col_names = FALSE)[, c(1,2)]
colnames(anki_cards) <- c("raw_char", "descr")

mypy_toneless = pydic(method = 'toneless')
mypy_normal = pydic(method = 'quanpin')
mypy_tone = pydic(method = 'tone')

# Testing
py("我", dic=mypy_toneless, sep="_")
py("我", dic=mypy_normal, sep="_")
py("我", dic=mypy_tone, sep="_")
```

## Generate parsed matrix

```{r}
target_anki_cards <- anki_cards %>% filter(!grepl("\\(", raw_char)) %>% filter(!grepl("<br>", raw_char))

meaning <- lapply(strsplit(target_anki_cards$descr, " "), 
       function(entry) {
           entry[3]
       }) %>% unlist() %>% 
    gsub("<br>.*", "", .) %>% 
    gsub("<div>.*", "", .) %>%
    gsub(",.*", "", .)
target_anki_cards$char <- target_anki_cards$raw_char %>% gsub("[ (].*", "", .)

all_chars_one_string <- paste(target_anki_cards$char, collapse="")
real_pinyin_string <- py(all_chars_one_string, dic=mypy_normal, sep="_")
real_pinyin <- strsplit(real_pinyin_string, "_") %>% unlist %>% unname()

all_chars_one_string_tone <- py(all_chars_one_string, dic=mypy_tone, sep="_")
all_chars_one_string_tone_split <- strsplit(all_chars_one_string_tone, "_") %>% unlist() %>% unname()
# all_chars_one_string_tone_split

tone_only <- vapply(all_chars_one_string_tone_split, function(pinyin_str) {
    
    full_split <- strsplit(pinyin_str, "")[[1]]
    full_split[length(full_split)]
}, "")

base_pinyin_only <- vapply(all_chars_one_string_tone_split, function(pinyin_str) {
    
    full_split <- strsplit(pinyin_str, "")[[1]]
    paste(full_split[1:length(full_split)-1], collapse="")
}, "")

write_tsv(target_anki_cards, path = "C:/Users/jakob/Desktop/test_out.tsv")

#real_pinyin/

nrow(target_anki_cards)
length(real_pinyin)

target_anki_cards$meaning <- meaning
target_anki_cards$pinyin <- real_pinyin
target_anki_cards$base_pinyin <- base_pinyin_only
target_anki_cards$tone <- tone_only

write_tsv(target_anki_cards, path="../Resources/anki.txt")

```


# Initial experiments follow below

Can be useful as source of possible commands for character conversions.

```{r}

tmcn::catUTF8("ŏ")
getCharset()

pinyins

vect <- c("我", "他", "你")
"我" %in% vect

vect <- c("wŏ", "tā", "nǐ")
"wŏ" %in% vect
"wo" %in% vect


"wŏ" %in% pinyins[1]

"xǚ" %in% pinyins

# out <- pinyin::py("我")

# byte[] bytes = Encoding.Unicode.GetBytes("string here");


rawToChar("77")

char1 <- charToRaw(pinyins[2])
char2 <- charToRaw("ŏ")

pinyins

rawToChar(char1)

char1 == char2


utf8ToInt("a")
intToUtf8(97)

as.hexmode(utf8ToInt("我"))
intToUtf8(25105)


utf8ToInt("o")
utf8ToInt("ŏ")
utf8ToInt("ǒ")
utf8ToInt("ō")
utf8ToInt("ó")
utf8ToInt("ò")
intToUtf8(111)

pinyins[1]

tone_threes %in% pinyins
#"ŏ" %in% 
strsplit(pinyins[1], "")[[1]]
n_of_u_chars("ŏ")
u_char("ŏ")
u_char_match("ŏ", "ŏ")
"\\ŏ" == unlist(strsplit(pinyins[1], ""))[2]
"\\ǒ" == unlist(strsplit(pinyins[1], ""))[2]
"ŏ" %in% unlist(strsplit(pinyins[1], ""))
pinyins[1]
tone_threes <- c("ă", "ě", "ǐ", "ǒ", "ǔ")
"ǒ" == "ŏ"

```






pinyin_codes <- c(
    "ā",
    "á",
    "ǎ",
    "à",
    "ē",      
    "é",
    "ě",
    "è",
    "ī",
    "í",
    "ǐ",
    "ì",
    "ǒ",
    "ò",
    "ū",
    "ú",
    "ǔ",
    "ù",  
    "ǚ"
)
